### ISSUE TITLE
Take2/Rockstar

### ISSUE THREAD

**Issue by SparkleCalibre** [rwengine/openrw#101]
There is a very big chance Rockstar will attempt to shut down this project, just like they did with  multiplayer mods for GTA V.
So this is the only idea I came up with:
1. Make game read data like textures, models, audio SFX from folders (not sure how that will be performance wise) instead of data archives. This will make modding a lil bit easier.
2. Name those textures, models, audio differently and maybe even make small edits to their structures.

Propose your ideas. Anything, that will give Rockstar as less ground to stand on as possible in case they'll try to attack.

**Comment by PureTryOut** [comment]
I don't think they would have any ground to stand on anyway. OpenRW asks the users to provide the data for them, they do not publish it themselves. It doesn't use any of their code either, it's all completely new. There is no copyright infringment being done here at all. And the assets will eventually be replaced for new ones anyway.

And besides, Take2 at the moment probably only cares about GTA5 anyway, since that is where they make money currently (with shark cards).

**Comment by christooss** [comment]
If I recall correctly game logic cannot be copyrighted/patented. So on that
front whole engine is of the hook if you don't distribute original game
assets (binaries,  textures, sounds etc.).

I will check for precedent of this kind of problems for projects (openttd
comes to mind). Openttd weren't sued but they tackled this with firstly not
distributing original files and later creating free (gpl?) assets even
creating 32bit versions of graphical files.

I can send an email to EFF with question about the issues that might arise
with "liberating" the code and assets.

**Comment by paulsapps** [comment]
With the GTA V mod they don't like it because it costs them business. If the mod makers released the source I don't think they have any legal rights to take that down, so then it would become a cat and mouse game of making MP mods stop working I suppose.

If the mod makers made a whole engine re-implementation like this one that would probably also give them zero grounds to take it down. You also have to remeber that the MP mods are using RockStars servers which might be why they can issue a C&D.

**Comment by JayFoxRox** [comment]
R* won't take it down. And even if they do nobody would care - just switch hosts and get on with it.
GTA3 is totally not what they are financially interested in at this point anyway (maybe if it was LCS or aimed at mobiles, but even then: meh).
All this does is provide tools to work with the game files in some way + the project goal is explicitly not piracy but portability. R* themself would make money if they sold GTA3 assets to users of OpenRW.
However, it would be a disaster if R* forbids modding in general (similar to the backlash you see on the FiveM action).

The situation with the GTA5 mods is completly unrelated and very different.
But even there R* doesn't have any control over it unless people use their servers.


Fortunately European law is very open to reverse engineering and ignoring invalid EULAs.

**Comment by JayFoxRox** [comment]
I'll just close this for now.
There are more important issues right now and this doesn't even seem to be an actual issue.

---

Feel free to open a new discussion if there is anything in particular where R* "might have a ground to stand on" (such as the CHASE array for the first mission which should probably not be hardcoded) with concrete ideas how we could change it.
