### ISSUE TITLE
Doesn't build on windows

### ISSUE THREAD

**Issue by hcorion** [rwengine/openrw#117]
> CMake Error at CMakeLists.txt:36 (message):
>   Unknown platform "Windows".  please update CMakeLists.txt.

I know, I know. Because I'm on windows I can play GTA 3 normally anyways. However, I would like to contribute to openrw, and I don't want to have to do it on my under-powered linux laptop. How easy would a port be? Would any of the core devs be willing to shed some light on this?

**Comment by paulsapps** [comment]
```
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
	add_definitions(-DRW_WINDOWS)
```

And handle as required? I.e whatever special stuff is done per platform for RW_LINUX,RW_FREEBSD or RW_OSX

**Comment by danhedron** [comment]
There are some places where the code assumes POSIX, such as when enumerating files. A windows port would need to use the appropriate windows APIs to do the same thing, or just not do it (since file-case fixing isn't required), along with the other platform-specific details such as configuration file location.

I'm happy to accept fixes for these things, along with anything that cleans up platform-specific code so it's not spread around the code.

**Comment by danhedron** [comment]
It's now possible to build the game on Windows as of #130. Work continues to make it easier to build with #182 and hopefully CI will be set up for Windows too once dependencies are readily available.
