### ISSUE TITLE
Two 8-Balls in the first mission 

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#134]
Hi

I noticed this bug in the game:

http://picpaste.com/Untitled13-HAExhpm7.png

**Comment by JayFoxRox** [comment]
This used to happen if 8-Ball is too far away from his respawn position. It usually happened on the second attempt of the mission but it could happen differently too (does it?)

---

OpenRW has had the [bad habit of replacing nearby characters which I have fixed since](https://github.com/rwengine/openrw/commit/340b2f715902d0a4ee5e1de9f32edba2fae573bc).
While this fixed this issue it was also completely wrong and caused (way more serious) bugs in other places (it would delete characters you are supposed to protect for example).

However, due to my change this should *always* happen now. It's a known issue.
- Just ignore useless characters for now.

---

The character *should* be removed either by https://github.com/Lighnat0r/GTA-III-SCM-Converted/blob/master/19_8ball.sc#L817 or the mission_cleanup opcode.
However, OpenRW currently doesn't implement this properly so unnecessary characters / vehicles / objects are kept around.

**Comment by danhedron** [comment]
#207 should fix this by introducing more correct cleanup behaviour that cleans up all types of objects, note just vehicles.
