### ISSUE TITLE
Write (and adhere to) contribution guidelines

### ISSUE THREAD

**Issue by danhedron** [rwengine/openrw#17]
Suggestions for code style
* Use google-ish convention for include guards: ``LIBRARY_FILE_HPP``
* document method behaviour if non-trivial
* Adhere to the style of the containing file
* Adopt a sensible variable naming convention:
  * Member Variable identification?
  * avoid single-letter variables outside counters

Progress
- [ ] Add GPL notice to header files
- [ ] Change existing header guards

Thoughts, @tsjost ?

**Comment by danhedron** [comment]
We have adopted a slightly modified version of the Google C++ clang-format for c++ style.

This is a bit of a meta-issue since the code is being changed to the new style as it is changed.

It may be worth it to push though a general coding standards change along with the clang format changes coming shortly.

**Comment by JayFoxRox** [comment]
Do we have guidelines for cmake yet? I feel there is a lot of style and variable naming mixing in that..

**Comment by danhedron** [comment]
I've updated the [Coding Conventions](https://github.com/rwengine/openrw/wiki/Coding-Conventions) page, we can add to the CMake style if any further issues come up.

**Comment by JayFoxRox** [comment]
I'm going through our prioritzed issues and this came up.
It feels like the original goal of this issue is completed. New rules can be added as part of the style PR.

The 2 tasks in this are - strangely - not really related to writing contribution guidelines (and not even strictly to "adhere" them either).
They don't have to be prioritized either and they'll likely be done as part of the style commits?
A lot of them have been added in the last few PRs too.

More concrete issues like "License header in files is missing" and "Header guards are not in same style" would be useful because they'll be well defined (much like "Write contribution guidelines" - which we kind of did now).

Either close this or remove it from the prioritzing list.
