### ISSUE TITLE
Provide openrw.ini

### ISSUE THREAD

**Issue by JayFoxRox** [rwengine/openrw#172]
[Generating/Bundling the openrw.ini should be automated](https://github.com/rwengine/openrw/wiki/Configuration).

Auto-generating it (if it's not found) has been suggested.

Another alternative to that would be to assume a default config and assume the game is in the current directory (for a gta3.exe drop-in replacement style binary).
Packagers could then attach a premade openrw.ini (included in this repo / extra repo) to their packages on Linux and other platforms if there is need for it.

We could also have a CLI to generate the config (probably in a platform dependent location) like X11 does.

I believe the original idea was to create an installer for platforms like Windows, though, I kind of dislike this idea.

**Comment by flatr0ze** [comment]
This engine can be used for Max Payne and pretty much any other game that came after GTA III from Rockstar with some modification. Since most likely this engine will be forked and adopted for those games, I could add my two cents and recommend you to rely on .ini files within game directories.
Generating the file through CLI might be pointless if you add flags for --game-files-dir and --custom-ini-config-file to specify custom configs and locations.
Unreal Engine got ported to GNU/Linux using that aforementioned "drop-in replacement" methodology, I believe it worked just well in case with UT99 and Rune ports by Loki Games.
