### ISSUE TITLE
Make it localizationable.

### ISSUE THREAD

**Issue by s8321414** [rwengine/openrw#21]
As title says, maybe we can get a localized game?

**Comment by tsjost** [comment]
This is certainly a good idea, especially since it's a thing in the original game. Maybe not the most prioritised thing right now, but it's something we have to keep in the back of our heads while developing!

**Comment by JayFoxRox** [comment]
I think this issue should be closed. It's in the realm of "allowing game mods".
- Ofcourse OpenRW will support loading different languages from the games GXT files.
So if you want to localize the game to a previously unsupported language, it should be enough to translate the GXT files. Wether OpenRW should feature a selection of more than the original languages is up for debate - I'd vote no, and claim this should be in some "OpenRW+" fork.

Any new text added by OpenRW is likely debug output which does not have to be localized; I don't think we'll reach a point where we need auto-translation tools to be honest

Thoughts?

**Comment by JayFoxRox** [comment]
We already allow setting the game language in the config now. The menu is using GXT strings too (mostly).

I'll close this for now.
It may be opened again if we, for one reason or another, decide to allow custom strings (unlikely).
If you want to support custom languages I recommend looking into GXT editors and, if necessary, creating a custom fontmap.
(This should be much easier once we support the japanese game, which may deserve an issue)

**Comment by s8321414** [comment]
hm...

**Comment by JayFoxRox** [comment]
hm...?

What I was trying to say is: Write [a file like this](https://github.com/Lighnat0r/Files/blob/master/GTA%203%20american.gxt%20source.txt) = translate every string in the game and store it in some unicode file. Then create a custom fontmap and list the letter kerning you'd want to use.
We'll probably be able to come up with a solution then (I believe the japanese version already loads font kerning from a txt file, but it's something we haven't investigated yet) and whip up a tool to do the actual GXT conversion for you (Making this compatible with the japanese version of the game and OpenRW).
Aside from kerning there is nothing preventing you from creating a localized version without modifications to OpenRW right now.

(Even the commercially available russian version of the game simply replaced french.gxt and provided a custom fontmap)

---

If your original question was about loading a chinese GXT / fontmap which already exists then it's a different issue. However, I've never seen / heard of such a GXT (and chances are that it would be the same style as the japanese one).

---

To see how to change the language at the moment, check the [wiki page about Configuration](https://github.com/rwengine/openrw/wiki/Configuration#game).
*Keep in mind that the russian version would require "french" as a language because that's what the publisher decided to go with..*
