### ISSUE TITLE
Can't proceed after 'Drive Misty For Me'

### ISSUE THREAD

**Issue by haphzd** [rwengine/openrw#257]
After ending cutscene control is not passed back to player, game would not switch from script camera to player camera.

**Comment by danhedron** [comment]
The problem is the script for this mission calls `01b4` to disable player input, but after the last cutscene never calls it to restore input.

I've pushed a fix for this to https://github.com/danhedron/openrw/tree/fix-mission-end-1. This resets player control when the game uses `0373`. However I'm not sure if this behaviour is correct, as `02ea` is also called at the end of the script so could be where this behaviour occurs.

**Comment by danhedron** [comment]
Committed the change for ``0373``, we can determine the exact correct behaviour later.
