### ISSUE TITLE
Windows version impossible to compile

### ISSUE THREAD

**Issue by erherhh4herh** [rwengine/openrw#304]
I admire the courageous efforts to re-create the executable of some of the best games ever. I tried to compile the windows version undergoing the, frankly ludicrous steps. The "OpenRW dependencies" don't seem to be linked anywhere apparent. I found them here: https://github.com/JayFoxRox/openrw-deps

After opening the "Update.sh", nothing happens. I cannot continue the visual studio solution file generation process without these dependencies. I'd recommend focusing on making the build steps on different platforms less clandestine. Now I know that you're active dev team is limited, I just wonder if this has anything to do with that. No need to try and help me with my current situation, it's clear you need time to flesh these things out. I'm willing to wait. Just posting this as a warning to those whom try to do the same as I.

**Comment by JayFoxRox** [comment]
Installing through MSYS is recommended and easy, follow the steps on https://github.com/rwengine/openrw/wiki/Building#mingw--msys .

The scripts linked above are for Microsoft Visual Studio. It's not OpenRW which is to blame in that case, but Microsoft for not providing proper ways to manage dependencies.
Similar repos exist for most cross-platform projects which want to support Microsoft Visual Studio.
Also see https://github.com/JayFoxRox/openrw/pull/15 for my progress on Microsoft Visual Studio support (which used to be WIP at the time of writing the "Building" wiki page, but has since been dropped, because a lack of users maintaining the MSVS deps).

I'm not a Windows user and still tried write those scripts (by popular demand). My motivation to work on them is very low as I wouldn't be using them. I'd rather have a Windows developer create those scripts. However, my experience with Windows users has been mostly negative: they usually lack motivation to work on anything unless it's essentially a fixed framework they just have to plug code into.

Note that there is no "dev team". OpenRW is an open-source project which depends on users to make the project work. There is no closed group / team. It's a project by and for the community.

I'd welcome anyone who wants to change my perception of Visual Studio users.

**Comment by erherhh4herh** [comment]
I apologize for my prior post. I was a bit discouraged by the lack of support of visual studio. I in no way meant to come off as condescending. I can totally understand that perception of yours... I come from a C# background where literally everything is laid out for you. I'm currently writing my own math library that's written entirely in C# without any external dependencies, because I was dumbfounded when I saw no other comprehensive/feature-rich libraries like it.... It's because windows users have a "If it ain't broke, don't fix it" mentality, disregarding the possibility for improvement. It's frankly shame-worthy :D

I just hope this project soon gets to a place where updated binaries are provided. Perhaps AppVeyor or similar? I can tell that the contributers are working hard and are active, so the wait for a fully playable, cross-platform GTA3 implementation shouldn't be too long :)

Unrelated question I'm sure has been asked before: Have you considered creating a discord/reddit (birthing a community)? I realize that doing so would attract a lot of genuinely stupid people, but it might also give this project a clear direction to follow. I know currently it's far too soon to do so, just wondered if that would ever be considered.

Thank you for your reply!

**Comment by darkf** [comment]
Should this still be open? The build instructions are pretty clear for Windows and it compiles fine.

@erherhh4herh It already has an IRC which the developers use, I don't see what value a Discord server would have.

**Comment by paulsapps** [comment]
Discord provides history and voice chat compared to IRC.

**Comment by JayFoxRox** [comment]
Closed because it's going offtopic.
If you feel need to discuss this further, please open new issues for each seperate issue (communication, compilation on different toolchains etc.)
