### ISSUE TITLE
HUD element flashing

### ISSUE THREAD

**Issue by danhedron** [rwengine/openrw#368]
Used in the intro sequence and when you get out of hospital.

Related Opcodes:
* [03E7](http://www.gtamodding.com/wiki/03E7) Flash HUD Object.

Notes:
The game HUD is drawn in DrawUI.cpp.

**Comment by CookiePLMonster** [comment]
Game flashes HUD elements by doing a `& 4` on an internal frame counter (so you get 3 frames of element not showing and 1 frame of element showing).

Since this behaviour is FPS dependant, I'd recommend making it timer based instead - 125ms off, 25ms on? Or 99 + 33 if you want to replicate default behaviour the most accurately.
