### ISSUE TITLE
Dropping gl_core_3_3?

### ISSUE THREAD

**Issue by ShFil119** [rwengine/openrw#514]
Tool for generating these files hasn't been updated from 2015.

It can be causing these errors:
 https://gist.github.com/ShFil119/6208b6c77856d4430ffa9e1ee56e8389

**Comment by JayFoxRox** [comment]
These are not part of gl_core_3_3.c but part of your GL driver (MESA in your case).
These are also false positives which you'd get with any other tool too.

I'm not sure if these are in the GL frontend or the i965 driver, but if they are in the intel portion (MMIO or something), then you can probably use `export LIBGL_ALWAYS_SOFTWARE=1` before running the game to use the MESA software renderer which might not be affected.

The tool probably hasn't been updated because it is working fine (unless you have more information by the tools author).

**Comment by christoph-heiss** [comment]
Also leaving my 2 cents:

Since we need these OpenGL declarations, dropping them is not really viable and beside that, they are working fine (as JayFoxRox pointed out).

I guess you could theoretically build the i965 driver with symbols included and report the issue upstream, but OpenRW can't do much about that.

**Comment by JayFoxRox** [comment]
These are not even issues upstream to my knowledge. I believe these are false-positives due to MMIO or memory permission issues (say.. passing a pointer via the kernel interfaces which valgrind doesn't know about).

**Comment by JayFoxRox** [comment]
Closed.

Reasons given by me and @christoph-heiss above.
If anyone want to change how we load GL / extensions, they can always open a new issue or PR; however, the current solution works and is not the source of these issues.
