### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by dolohow** [rwengine/openrw#85]
Do you guys accept donations?

**Comment by JayFoxRox** [comment]
I'm not sure. What would the benefit of this be?

(The rest of this post is mostly not directly OpenRW related but just my general thoughts about donations)

I personally accept donations, but I'm often just one of the contributors and I don't (want to) take project related donations (especially OpenRW). It's always hard to decide for teams who should get how much money or what it will be used for (maybe developer meetups?).

I'd feel like stealing if I received money for a project which I only worked on for a couple of days if somebody spend years (like @danhedron ) working on it. However, if @danhedron receives money for it I'd not be motivated to work on it any longer either because I don't feel like working on something for free when somebody else higher up receives money for it.
I also dislike the idea of receiving money upfront because it creates the obligation to work on something which should be a hobby and relaxing.

If you like my work (on either of my projects) feel free to donate to me personally.
However, only donate if you can tell what I contributed and you are certain it's me who you want to donate to (and not the person who took years to lay the groundwork before). In the end it's up to the person donating to make sure their money is going to the right person.

Also FYI: I've made exactly $0 (zero) in cash donations across all my projects so far (I got some free hardware though + I've sold some code for good money before which was created as a hobby).
(Ideally I'd pay rent and new notebooks from donations, but I don't think it will ever happen)

**Comment by dakk** [comment]
You can use a service like this https://www.bountysource.com/ to split the project in many "bounties"; who make the bounty will receive the assigned amount ;)

**Comment by JayFoxRox** [comment]
via IRC:

```
JayFoxRox: we still haven't discussed/closed the donation issue btw. we should consider allowing donations until a pot is full. the money could be used to buy additional domains, pay for a lawyer to verify how we have to spell "GTA3(R)(C) all rights belong to R*" and maybe we could use some money to buy international releases of GTA for a collection we can share accross devs?
JayFoxRox: whenever we have too much money we could just donate the rest to EFF, MSF or prevent cancer or something - maybe donate during agdq or something in the GTA runs for extra publicity too
JayFoxRox: there are certainly some good uses for the money which I didn't consider before
JayFoxRox: I still believe paying developers or bounties is a bad idea though

PureTryOut: I would say accept all the donations, use what you need for indeed copies of the games, domain costs, etc, and donate everything you have leftover to either other FOSS projects, or charity

douglas: consider https://sfconservancy.org
```

**Comment by danhedron** [comment]
We're not currently looking to solicit any form of donations.
